#!/bin/bash
SERVER_CONF=$CATALINA_HOME/conf/server.xml
cp $CATALINA_HOME/server.xml $SERVER_CONF

sed -i 's|@TCS_CATALOG_URL@|'"$TCS_CATALOG_URL"'|g' $SERVER_CONF
sed -i 's|@TCS_CATALOG_USERNAME@|'"$TCS_CATALOG_USERNAME"'|g' $SERVER_CONF
sed -i 's|@TCS_CATALOG_PASSWORD@|'"$TCS_CATALOG_PASSWORD"'|g' $SERVER_CONF
sed -i 's|@OLTP_URL@|'"$OLTP_URL"'|g' $SERVER_CONF
sed -i 's|@OLTP_USERNAME@|'"$OLTP_USERNAME"'|g' $SERVER_CONF
sed -i 's|@OLTP_PASSWORD@|'"$OLTP_PASSWORD"'|g' $SERVER_CONF

exec "$@"
